import type { Metadata } from "next";
import "./globals.css";
import ReduxRegistry from "@/components/Redux/ReduxRegistry";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxRegistry>
        <body>
          {children}
        </body>
      </ReduxRegistry>
    </html>
  );
}
